apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: server
spec:
  serviceName: keycloak
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/component: server
    spec:
      containers:
      - name: keycloak
        image: docker.io/bitnamilegacy/keycloak:26.3.3-debian-12-r0
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        - name: discovery
          containerPort: 7800
          protocol: TCP
        env:
        # Bitnami Keycloak admin credentials (KC_BOOTSTRAP_* is used by Bitnami)
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: user
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secrets
              key: admin-password
        # Bitnami database configuration (KC_DB_URL is complete JDBC connection string)
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: "jdbc:postgresql://postgresql:5432/bitnami_keycloak?currentSchema=public"
        - name: KC_DB_SCHEMA
          value: public
        - name: KC_DB_USERNAME
          value: bn_keycloak
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secrets
              key: postgres-password
        # Bitnami Keycloak configuration
        - name: BITNAMI_DEBUG
          value: "false"
        - name: KC_HTTP_PORT
          value: "8080"
        - name: KC_HTTPS_PORT
          value: "8443"
        - name: KC_HTTP_MANAGEMENT_PORT
          value: "9000"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HTTP_RELATIVE_PATH
          value: "/"
        - name: KC_LOG_CONSOLE_OUTPUT
          value: "default"
        - name: KC_LOG_LEVEL
          value: "INFO"
        - name: KC_SPI_ADMIN_REALM
          value: "master"
        - name: KEYCLOAK_PRODUCTION
          value: "false"
        - name: KC_PROXY
          value: "edge"
        - name: KC_METRICS_ENABLED
          value: "false"
        - name: KC_CACHE
          value: "ispn"
        - name: KC_CACHE_STACK
          value: "jdbc-ping"
        - name: KC_CACHE_CONFIG_FILE
          value: "cache-ispn.xml"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 750m
            memory: 768Mi
        livenessProbe:
          httpGet:
            path: /realms/master
            port: http
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /realms/master
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3