apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
type: Opaque
stringData:
  admin-password: changeme123  # Change in production
  postgres-password: postgres123  # Change in production